version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile  
    ports:
      - "8080:8080"                # Map container port 8080 to host port 8080
    environment:
      - PORT=8080

    # volumes:
    #   - ./app:/app
    #   - ./frontend:/frontend_build
