version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile  
    ports:
      - "8080:8080"                # Map container port 8080 to host port 8080
    environment:
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # For development:
    # volumes:
    #   - ./backend/app:/app/app
    #   - ./frontend:/app/static/frontend
    #   - ./index.html:/app/index.html
